Here is an exmaple of usage for the main class of `neural-semigroups` package, `CayleyDatabase`.
First, we need to create a database. By default, is downloads data from `smallsemi` package of [the GAP system](https://www.gap-system.org). It provides easily accessable data files for semigroups of cardinality from 2 to 7. In this example we will use cardinality 5. Downloading data from the internet can take minutes but is done only once. Loading data to memory still can take several seconds on any re-iteration.

In [5]:
%%time
from neural_semigroups.cayley_database import CayleyDatabase

cayley_db = CayleyDatabase(cardinality=7)

CPU times: user 8.33 s, sys: 144 ms, total: 8.47 s
Wall time: 8.47 s


In [6]:
total_tables = cayley_db.database.shape[0]
print(f"{total_tables} entires loaded")

836021 entires loaded


Each entry of the Cayley database of cardinality 3 is a `numpy` array which is denoted by the following Python code:
<pre>
np.array([
    [0, 1, 2],
    [1, 2, 0],
    [2, 0, 1]
])
</pre>

This code corresponds to a Cayley table

|*|0|1|2|
|-|-|-|-|
|0|0|1|2|
|1|1|2|0|
|2|2|0|1|

i.e. $1 * 1 = 2$, $2 * 1 = 0$, etc.

Let's take a look at some etries from our database (of different cardinality).

In [7]:
import numpy as np

print(cayley_db.database[np.random.randint(0, total_tables)])
print(cayley_db.database[np.random.randint(0, total_tables)])

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 1 1 0]
 [0 0 0 1 1 0 0]
 [0 0 0 1 0 1 1]
 [0 0 1 0 0 1 1]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1]
 [0 0 1 0 1 0 1]
 [0 0 0 1 0 1 1]
 [0 0 1 0 1 1 1]]
